[package]
name = "bflib_proc_macro"
version = "0.1.5"
edition = "2021"

description = "proc macro of bflib"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"